export const storeProducts = [{
    id: 1,
    price: 299,
    title: "black top",
    img: "img/black-top.jpg",
    imgOver: "img/black-top2.jpg",
    moreImg: ["img/black-top.jpg", "img/black-top1.jpg", "img/black-top2.jpg", "img/black-top3.jpg", "img/black-top4.jpg", "img/black-top5.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 2,
    price: 299,
    title: "beige top",
        img: "img/beige-top.jpg",
        imgOver: "img/beige-top1.jpg",
    moreImg: ["img/beige-top.jpg", "img/beige-top1.jpg", "img/beige-top2.jpg","img/beige-top3.jpg","img/beige-top4.jpg",],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 3,
    price: 399,
    title: "blue long sleeve",
        img: "img/blue-electrician-longsleeve.jpg",
        imgOver: "img/blue-electrician-longsleeve3.jpg",
    moreImg: ["img/blue-electrician-longsleeve.jpg","img/blue-electrician-longsleeve1.jpg","img/blue-electrician-longsleeve2.jpg","img/blue-electrician-longsleeve3.jpg",],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 4,
    price: 399,
    title: "white long sleeve",
        img: "img/white-longsleeve.jpg",
        imgOver: "img/white-longsleeve1.jpg",
    moreImg: ["img/white-longsleeve.jpg", "img/white-longsleeve1.jpg", "img/white-longsleeve2.jpg", "img/white-longsleeve3.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 5,
    price: 399,
    title: "black long sleeve",
        img: "img/black-longsleeve.jpg",
        imgOver: "img/black-longsleeve1.jpg",
    moreImg: ["img/black-longsleeve.jpg", "img/black-longsleeve1.jpg", "img/black-longsleeve2.jpg", "img/black-longsleeve3.jpg"],
    info: "",
    inCart: false,
    count: 0,
    total: 0
}, {
    id: 6,
    price: 450,
    title: "white t-shirt",
        img: "img/white-tshirt.jpg",
        imgOver: "img/white-tshirt1.jpg",
    moreImg: ["img/white-tshirt.jpg","img/white-tshirt1.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 7,
    price: 450,
    title: "black t-shirt",
        img: "img/black-tshirt.jpg",
        imgOver: "img/black-tshirt1.jpg",
    moreImg: ["img/black-tshirt.jpg", "img/black-tshirt1.jpg", "img/black-tshirt2.jpg", "img/black-tshirt3.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 8,
    price: "999",
    title: "black leather dress",
        img: "img/black-dress.jpg",
        imgOver: "img/black-dress1.jpg",
    moreImg: ["img/black-dress.jpg", "img/black-dress1.jpg", "img/black-dress2.jpg", "img/black-dress3.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 9,
    price: 1700,
    title: "black sportsuit",
        img: "img/black-sportsuit.jpg",
        imgOver: "img/black-sportsuit1.jpg",
    moreImg: ["img/black-sportsuit.jpg", "img/black-sportsuit1.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
},{
    id: 10,
    price: 1700,
    title: "grey sportsuit",
        img: "img/grey-sportsuit.jpg",
        imgOver: "img/grey-sportsuit1.jpg",
    moreImg: ["img/grey-sportsuit.jpg", "img/grey-sportsuit1.jpg", "img/grey-sportsuit2.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 11,
    price: 1700,
    title: "dark blue suit",
        img: "img/darkblue-suit.jpg",
        imgOver: "img/darkblue-suit1.jpg",
    moreImg: ["img/darkblue-suit.jpg", "img/darkblue-suit1.jpg", "img/darkblue-suit2.jpg", "img/darkblue-suit3.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 12,
    price: 475,
    title: "brown long sleeve",
        img: "img/brown-one-shoulder.jpg",
        imgOver: "img/brown-one-shoulder1.jpg",
    moreImg: ["img/brown-one-shoulder.jpg", "img/brown-one-shoulder1.jpg", "img/brown-one-shoulder2.jpg",],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 13,
    price: 475,
    title: "grey long sleeve",
        img: "img/grey-one-shoulder.jpg",
        imgOver: "img/grey-one-shoulder1.jpg",
    moreImg: ["img/grey-one-shoulder.jpg", "img/grey-one-shoulder1.jpg", "img/grey-one-shoulder2.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 14,
    price: 475,
    title: "black long sleeve ",
        img: "img/black-one-shoulder.jpg",
        imgOver: "img/black-one-shoulder1.jpg",
    moreImg: ["img/black-one-shoulder.jpg", "img/black-one-shoulder1.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 15,
    price: 2150,
    title: "white down jacket",
        img: "img/white-down-jacket.jpg",
        imgOver: "img/white-down-jacket1.jpg",
    moreImg: ["img/white-down-jacket.jpg", "img/white-down-jacket1.jpg", "img/white-down-jacket2.jpg", "img/white-down-jacket3.jpg", "img/white-down-jacket4.jpg",],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 16,
    price: 2150,
    title: "black down jacket",
        img: "img/black-down-jacket.jpg",
        imgOver: "img/black-down-jacket1.jpg",
    moreImg: ["img/black-down-jacket.jpg", "img/black-down-jacket1.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 17,
    price: 799,
    title: "black leather shorts",
        img: "img/black-shorts.jpg",
        imgOver: "img/black-shorts1.jpg",
    moreImg: ["img/black-shorts.jpg","img/black-shorts1.jpg","img/black-shorts2.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 18,
    price: 1100,
    title: "long blue dress",
        img: "img/blue-dress.jpg",
        imgOver: "img/blue-dress1.jpg",
    moreImg: ["img/blue-dress.jpg", "img/blue-dress1.jpg", "img/blue-dress2.jpg", "img/blue-dress3.jpg", "img/blue-dress4.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}, {
    id: 19,
    price: 1250,
    title: "white short dress",
        img: "img/whire-dress.jpg",
        imgOver: "img/whire-dress3.jpg",
    moreImg: ["img/whire-dress.jpg", "img/whire-dress1.jpg", "img/whire-dress2.jpg", "img/whire-dress3.jpg", "img/whire-dress4.jpg"],
    info: "",
    size: ["xs","s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
}];

export const detailProduct = {
    id: 1,
    price: 299,
    title: "black top",
    img: "img/black-top.jpg",
    imgOver: "img/black-top1.jpg",
    moreImg: ["img/black-top.jpg",  "img/black-top2.jpg", "img/black-top3.jpg",  "img/black-top5.jpg"],
    info: "",
    size: ["xs", "s", "m", "l", "xl"],
    inCart: false,
    selectedSize: "",
    count: 0,
    total: 0
};